baseurl = "http://localhost/"
contentdir = "content"
languageCode = "en-us"
title = "Docker Docs"
theme = "hugo-foundation"
canonifyurls = false
relativeURLs = true

[blackfriday]
  fractions = false
  plainIdAnchors = true
  gitHubLinkEval = true

# Menu configuration should come last in this file;
# leave at least one blank line at the end
#
# INSTALL Menu
#
[[menu.main]]
	name = "Install"
	identifier = "mn_install"
	weight = 1
[[menu.main]]
	name = "Docker Engine"
	identifier = "smn_engine"
	parent = "mn_install"
	weight = 1
[[menu.main]]
	name = "Linux"
	identifier = "smn_linux"
	parent = "smn_engine"
	weight = 80
[[menu.main]]
	name = "Cloud"
	identifier = "smn_cloud"
	parent = "smn_engine"
	weight = 99
#
# Use Docker Menu
#
[[menu.main]]
	name = "Docker Fundamentals"
	identifier = "mn_fun_docker"
	weight = 2
[[menu.main]]
	name = "Work with Docker Images"
	identifier = "smn_images"
	parent = "mn_fun_docker"
	weight = 1
[[menu.main]]
	name = "Work with Docker Containers"
	identifier = "smn_containers"
	parent = "mn_fun_docker"
	weight = 3
[[menu.main]]
	name = "Use the Kitematic GUI"
	identifier = "smn_workw_kitematic"
	parent = "mn_fun_docker"
	weight = 5
[[menu.main]]
	name = "Docker on Windows & OSX"
	identifier = "smn_win_osx"
	parent = "mn_fun_docker"
	weight = 4
#
#  Build, Ship, Run
#
[[menu.main]]
	name = "Use Docker"
	identifier = "mn_use_docker"
	weight = 3
[[menu.main]]
	name = "Provision & set up Docker hosts"
	identifier = "smn_workw_machine"
	parent = "mn_use_docker"
	weight = 2
[[menu.main]]
	name = "Create multi-container applications"
	identifier = "smn_workw_compose"
	parent = "mn_use_docker"
	weight = 3
[[menu.main]]
	name = "Cluster Docker containers"
	identifier = "smn_workw_swarm"
	parent = "mn_use_docker"
	weight = 4
[[menu.main]]
	name = "Administrate Docker"
	identifier = "smn_administrate"
	parent = "mn_use_docker"
	weight = 6
[[menu.main]]
	name = "Applications and Services"
	identifier = "smn_apps_servs"
	parent = "smn_administrate"
	weight = 100
[[menu.main]]
	name = "Integrate with Third-party Tools"
	identifier = "smn_third_party"
	parent = "smn_administrate"
	weight = 101
#
# HUB Menu
#
[[menu.main]]
	name = "Manage image repositories"
	identifier = "mn_docker_hub"
	weight = 5
[[menu.main]]
	name = "Docker Hub"
	identifier = "smn_pubhub"
	parent = "mn_docker_hub"
	weight = 1
[[menu.main]]
	name = "Docker Trusted Registry"
	identifier = "smn_dhe"
	parent = "mn_docker_hub"
	weight = 2
[[menu.main]]
	name = "DTR APIs"
	identifier = "smn_dtrapi"
	parent = "smn_dhe"
	weight = 99
[[menu.main]]
	name = "Docker Registry"
	identifier = "smn_registry"
	parent = "mn_docker_hub"
	weight = 3
#
# Command and API Reference
#
[[menu.main]]
	name = "Command and API references"
	identifier = "mn_reference"
	weight = 7
[[menu.main]]
	name = "Command line reference"
	identifier = "smn_cli"
 	parent = "mn_reference"
[[menu.main]]
	name = "Docker Remote API"
	identifier = "smn_remoteapi"
	parent = "mn_reference"
	weight = 1
[[menu.main]]
	name = "Docker Hub"
	identifier = "smn_hub_ref"
	parent = "mn_reference"
	weight = 2
[[menu.main]]
	name = "Docker Compose Reference"
	identifier = "smn_compose_ref"
	parent = "mn_reference"
	weight = 3
[[menu.main]]
	name = "Docker Machine Reference"
	identifier = "smn_machine_ref"
	parent = "mn_reference"
	weight = 4
[[menu.main]]
	name = "Docker Swarm Reference"
	identifier = "smn_swarm_ref"
	parent = "mn_reference"
	weight = 5
[[menu.main]]
	name = "Docker Registry Reference"
	identifier = "smn_registry_ref"
	parent = "mn_reference"
	weight = 6
#
# Open source at Docker
#
[[menu.main]]
	name = "Open Source at Docker"
	identifier = "mn_opensource"
	weight = 8
[[menu.main]]
	name = "Configure Development Environment"
	identifier = "smn_develop"
	parent = "mn_opensource"
	weight = 2
[[menu.main]]
	name = "Contribution Workflow"
	identifier = "smn_contribute"
	parent = "mn_opensource"
	weight = 3
[[menu.main]]
	name = "Governance"
	identifier = "smn_governance"
	parent = "mn_opensource"
	weight = 9
#
# About
#
[[menu.main]]
	name = "About"
	identifier = "mn_about"
	weight = 9
#
# Version
#
[[menu.main]]
	name = "Docs archive"
	identifier = "mn_versions"
	weight = 10
[[menu.main]]
	name = "Version 1.7"
	identifier = "smn_seventeen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.7/"
	weight = -1
[[menu.main]]
	name = "Version 1.6"
	identifier = "smn_sixteen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.6/"
	weight = 1
[[menu.main]]
	name = "Version 1.5"
	identifier = "smn_fifteen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.5/"
	weight = 2
[[menu.main]]
	name = "Version 1.4"
	identifier = "smn_fourteen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.4/"
	weight = 3

