baseurl = "http://localhost/"
contentdir = "content"
languageCode = "en-us"
title = "Docker Docs"
theme = "hugo-foundation"
canonifyurls = false
relativeURLs = true
verbose = true

[blackfriday]
  fractions = false
  smartDashes = false
  plainIDAnchors = true
  sourceRelativeLinksEval = true

# Menu configuration should come last in this file;
# leave at least one blank line at the end
#
[[menu.main]]		
   name = "API reference"
   parent = "docker-cloud"
   url = "/apidocs/docker-cloud/"
   weight = 90
#
# Component projects is a menu for Registry/Notary etc.
#
[[menu.main]]
	name = "Component Projects"
	identifier = "mn_components"
	weight = 8

#
# About
#
[[menu.main]]
	name = "About"
	identifier = "mn_about"
	weight = 9
#
# Version
#
[[menu.main]]
	name = "Docs archive"
	identifier = "mn_versions"
	weight = 10
[[menu.main]]
	name = "Version 1.9"
	identifier = "smn_nineteen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.9/"
	weight = -1
[[menu.main]]
	name = "Version 1.8"
	identifier = "smn_eightteen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.8/"
	weight = 1
[[menu.main]]
	name = "Version 1.7"
	identifier = "smn_seventeen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.7/"
	weight = 2
[[menu.main]]
	name = "Version 1.6"
	identifier = "smn_sixteen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.6/"
	weight = 3
[[menu.main]]
	name = "Version 1.5"
	identifier = "smn_fifteen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.5/"
	weight = 4
[[menu.main]]
	name = "Version 1.4"
	identifier = "smn_fourteen"
	parent = "mn_versions"
	url = "http://docs.docker.com/v1.4/"
	weight = 5
